version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
cache: packages -> **\packages.config
nuget:
  account_feed: true
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  verbosity: minimal
  #parallel: true
#environment:
  #Test1: Test1_from_yml
after_build:
- msbuild %APPVEYOR_PROJECT_NAME%.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" -p:Configuration=Debug /t:Package /p:PackageLocation=./%APPVEYOR_PROJECT_NAME%_Staging.zip /p:DeployOnBuild=True /p:PublishProfile=appveyor
artifacts:
- path: '*.zip'
  name: artifacts